# help_game_multiplayer.py
# Panduan Universal Infrastruktur Game Multiplayer (nzr-game)

print("=" * 65)
print("     PANDUAN UNIVERSAL SYSTEM MULTIPLAYER (SERVER & IP)")
print("=" * 65)
print()

print("--- [ 1. STRUKTUR REPOSITORI UNIVERSAL ] ---")
print("Setiap sub-game multiplayer dalam proyek ini memiliki 3 komponen utama:")
print("1. server.py -> Mengelola logika multiplayer & koneksi WebSocket (Port 8765).")
print("2. ip.py     -> Mendeteksi jaringan & menjalankan HTTP Server (Port 8000).")
print("3. index.html-> Tampilan game/client yang diakses oleh pemain.")
print()

print("--- [ 2. LANGKAH BESAR: PERSIAPAN JARINGAN ] ---")
print("Agar pemain lain (Client) bisa terhubung ke HP Utama (Server):")
print("1. Aktifkan Hotspot Portabel pada HP yang bertindak sebagai Server.")
print("2. Minta semua HP teman (Client) untuk masuk/konek ke Hotspot tersebut.")
print("   *Catatan: Game tetap bisa berjalan tanpa kuota internet.")
print()

print("--- [ 3. LANGKAH DETAIL: MENJALANKAN BACKEND MULTIPLAYER ] ---")
print("1. Buka Termux, masuk ke folder game pilihan Anda (misal: cd gloff).")
print("2. Jalankan Server WebSocket utama dengan perintah:")
print("   python server.py")
print("3. Biarkan terminal ini tetap berjalan (jangan ditutup) karena sesi")
print("   permainan seluruh pemain diproses secara terpusat di sini.")
print()

print("--- [ 4. LANGKAH DETAIL: OTOMATISASI IP & HTTP PORTAL ] ---")
print("1. Buka Sesi Baru (New Session) di Termux, masuk ke folder yang sama.")
print("2. Jalankan skrip detektor IP dengan perintah:")
print("   python ip.py")
print("3. Perhatikan output 'INFORMASI KONEKSI' pada layar terminal:")
print("   - IP HOTSPOT (ap0) -> Muncul jika Anda membuka hotspot portabel.")
print("   - IP WIFI (wlan0)   -> Muncul jika Anda menggunakan WiFi lokal bersama.")
print("   - IP LOCALHOST      -> Digunakan jika Anda ingin bermain/tes sendiri.")
print()

print("--- [ 5. LANGKAH DETAIL: CARA MENGAKSES DAN BERMAIN ] ---")
print("1. UNTUK HP SERVER (Anda sendiri):")
print("   - Buka browser, masuk ke URL: http://127.0.0.1:8000/index.html")
print("   - Masukkan IP local/hotspot Anda di kolom sambungan game.")
print()
print("2. UNTUK HP TEMAN (Pemain Lain / Client):")
print("   - Buka browser di HP mereka, ketik URL HTTP Server yang tertera")
print("     pada terminal ip.py (Contoh: http://192.168.43.1:8000/index.html).")
print("   - Pada panel 'Sambungkan ke Server', masukkan alamat IP Hotspot Anda.")
print("   - Klik Hubungkan/Join, masukkan nama pemain, dan mulai bermain!")
print()

print("--- [ 6. ATURAN PENGEMBANGAN GAME BARU KE DEPAN ] ---")
print("Jika Anda ingin membuat game multiplayer baru lagi di dalam folder lain:")
print("1. Gunakan Port 8765 untuk WebSocket Server agar seragam.")
print("2. Gunakan Port 8000 untuk HTTP Server pada skrip ip.py Anda.")
print("3. Pastikan skrip ip.py selalu diletakkan berdampingan dengan index.html")
print("   dari game yang ingin Anda jalankan saat itu.")
print()

print("=" * 65)
print("  Status Jaringan Selalu Tersimpan Otomatis di file ip_config.js  ")
print("=" * 65)
