#!/usr/bin/env python3
"""
ip.py - Helper Script untuk Game Multiplayer (Universal)
Fungsi:
1. Auto-detect IP Hotspot (ap0) dan WiFi (wlan0) via global ifconfig sifting
2. Serve index.html via HTTP server di port 8000
3. Tampilkan info koneksi lengkap untuk para pemain

Cara pakai:
  python ip.py
"""

import socket
import subprocess
import re
import os
import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler
import time

HTTP_PORT = 8000

def get_ip_from_ifconfig_global():
    """Mengambil semua data ifconfig sekaligus untuk menghindari masalah izin Android"""
    try:
        # Jalankan ifconfig secara global untuk memotong batasan permission interface spesifik
        result = subprocess.run(['ifconfig'], capture_output=True, text=True, timeout=5)
        return result.stdout
    except Exception:
        return ""

def get_all_ips():
    """Deteksi semua IP yang tersedia dengan menyaring output global"""
    raw_output = get_ip_from_ifconfig_global()
    
    ips = {
        'hotspot': None,    # ap0
        'wifi': None,       # wlan0
        'localhost': '127.0.0.1'
    }

    # Gunakan Regex DOTALL untuk mengekstrak ip dari blok interface yang tepat
    # Saring IP Hotspot (ap0)
    ap0_match = re.search(r'ap0:.*?\n\s+inet\s+(\d+\.\d+\.\d+\.\d+)', raw_output, re.DOTALL)
    if ap0_match:
        ips['hotspot'] = ap0_match.group(1)
        
    # Saring IP WiFi (wlan0)
    wlan0_match = re.search(r'wlan0:.*?\n\s+inet\s+(\d+\.\d+\.\d+\.\d+)', raw_output, re.DOTALL)
    if wlan0_match:
        ips['wifi'] = wlan0_match.group(1)

    # Fallback: jika metode sifting di atas kosong, coba gunakan hostname
    try:
        hostname = socket.gethostname()
        ips['hostname_ip'] = socket.getaddrinfo(hostname, None, socket.AF_INET)[0][4][0]
    except Exception:
        ips['hostname_ip'] = None

    return ips

def print_banner(ips):
    """Tampilkan info koneksi yang rapi"""
    print("=" * 55)
    print("  🎮 MULTIPLAYER GAME - IP DETECTOR & HTTP SERVER")
    print("=" * 55)
    print()
    print("  📡 INFORMASI KONEKSI:")
    print("  " + "-" * 51)

    if ips['hotspot']:
        print(f"  🔥 IP HOTSPOT (ap0):     {ips['hotspot']}")
        print(f"     → Teman connect ke:  ws://{ips['hotspot']}:8765")
        print()
    else:
        print("  ❌ Hotspot tidak aktif / tidak terdeteksi")
        print()

    if ips['wifi']:
        print(f"  📶 IP WIFI (wlan0):     {ips['wifi']}")
        print(f"     → Jika di WiFi sama: ws://{ips['wifi']}:8765")
        print()

    print(f"  🏠 IP LOCALHOST:         {ips['localhost']}")
    print(f"     → Anda main sendiri: ws://{ips['localhost']}:8765")
    print()
    print("  " + "-" * 51)
    print("  🌐 HTTP SERVER (untuk serve index.html):")
    print(f"     http://{ips['localhost']}:{HTTP_PORT}/index.html")

    if ips['hotspot']:
        print(f"     http://{ips['hotspot']}:{HTTP_PORT}/index.html")

    if ips['wifi']:
        print(f"     http://{ips['wifi']}:{HTTP_PORT}/index.html")

    print()
    print("  " + "=" * 55)
    print("  📋 CARA PAKAI:")
    print("  " + "-" * 51)
    print("  1. Pastikan server.py sudah jalan di terminal lain:")
    print("     python server.py")
    print()
    print("  2. Buka browser di HP ini, ketik:")
    print(f"     http://{ips['localhost']}:{HTTP_PORT}/index.html")
    print()
    print("  3. Di panel 'Sambungkan ke Server', masukkan:")

    if ips['hotspot']:
        print(f"     {ips['hotspot']}  (untuk semua pemain)")
    else:
        print(f"     {ips['wifi'] or ips['localhost']}  (IP WiFi/Local)")

    print()
    print("  4. Klik 'Join Game' → masukkan nama → main!")
    print("=" * 55)
    print()

def start_http_server():
    """Jalankan HTTP server untuk serve index.html"""

    # Cek apakah index.html ada di folder ini
    if not os.path.exists('index.html'):
        print("❌ ERROR: index.html tidak ditemukan di folder ini!")
        print(f"   Folder saat ini: {os.getcwd()}")
        print("   Pastikan ip.py dijalankan di folder yang sama dengan index.html")
        sys.exit(1)

    handler = SimpleHTTPRequestHandler
    httpd = HTTPServer(('0.0.0.0', HTTP_PORT), handler)

    print(f"🚀 HTTP Server berjalan di port {HTTP_PORT}...")
    print(f"   Tekan Ctrl+C untuk berhenti\n")

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n🛑 Server dihentikan.")
        httpd.shutdown()

def main():
    print("🔍 Mendeteksi IP network secara aman...\n")

    ips = get_all_ips()
    print_banner(ips)

    # Simpan IP ke file config untuk index.html (optional)
    config_js = f"""// Auto-generated by ip.py
// Hotspot IP: {ips['hotspot'] or 'NOT_FOUND'}
// WiFi IP: {ips['wifi'] or 'NOT_FOUND'}
"""
    with open('ip_config.js', 'w') as f:
        f.write(config_js)

    print("💾 IP config tersimpan di ip_config.js")
    print("🌐 Memulai HTTP server...\n")
    time.sleep(1)

    start_http_server()

if __name__ == "__main__":
    main()
