# help_game_multiplayer.py
# Panduan Lengkap Penggunaan Game Multiplayer Mini Golf (Updated dengan ip.py)

print("=" * 65)
print("             PANDUAN LENGKAP GAME MULTIPLAYER MINI GOLF             ")
print("=" * 65)
print()

print("--- [ LANGKAH 1: PERSIAPAN UTAMA (JARINGAN & REPO) ] ---")
print("1. Pastikan semua file utama (index.html, server.py, ip.py) berada")
print("   dalam satu folder yang sama di Termux.")
print("2. Jika ingin bermain multiplayer bersama teman:")
print("   - Aktifkan Hotspot Portabel di HP Server.")
print("   - Pastikan HP Teman (Client) sudah terhubung ke Hotspot tersebut.")
print()

print("--- [ LANGKAH 2: MENJALANKAN GAME ENGINE (SERVER) ] ---")
print("1. Buka aplikasi Termux (Sesi 1), masuk ke folder proyek.")
print("2. Jalankan backend server dengan perintah:")
print("   python server.py")
print("3. Biarkan terminal ini tetap terbuka untuk memproses pergerakan bola,")
print("   deteksi masuk lubang, penalti OOB, dan sinkronisasi pemain.")
print()

print("--- [ LANGKAH 3: OTOMATISASI IP & HTTP SERVER (INFO TERPERINCI) ] ---")
print("1. Buka Sesi Baru (Sesi 2) di Termux, masuk ke folder yang sama.")
print("2. Jalankan skrip pembantu koneksi dengan perintah:")
print("   python ip.py")
print("3. Skrip ini akan otomatis memindai interface jaringan Anda:")
print("   - Jika Hotspot aktif, baris 'IP HOTSPOT (ap0)' akan terisi.")
print("   - Jika terhubung WiFi, baris 'IP WIFI (wlan0)' akan terisi.")
print("4. Catat alamat IP yang ditampilkan pada banner 'INFORMASI KONEKSI'.")
print()

print("--- [ LANGKAH 4: MENGAKSES DAN MENYAMBUNGKAN CLIENT ] ---")
print("1. DI HP SERVER (Anda sendiri):")
print("   - Buka browser, akses URL Localhost: http://127.0.0.1:8000/index.html")
print("   - Pada panel pop-up sambungkan server, biarkan terisi IP default:")
print("     192.168.43.1 (atau sesuaikan dengan IP ap0 Anda).")
print("2. DI HP TEMAN (Client):")
print("   - Buka browser, ketik URL HTTP Server yang tertera di terminal ip.py")
print("     (Contoh: http://192.168.43.1:8000/index.html)")
print("   - Masukkan IP Hotspot Server Anda pada kolom panel penyambung.")
print("3. Pastikan indikator status di pojok kanan atas HUD berubah jadi 'Online'.")
print()

print("--- [ LANGKAH 5: BERGABUNG DAN DETAIL MEKANIK ARENA ] ---")
print("1. Klik tombol '➕ Join Game' di layar browser masing-masing.")
print("2. Masukkan nama pemain unik (maksimal 12 karakter) lalu tekan enter.")
print("3. Game berjalan secara Turn-Based (bergantian):")
print("   - Perhatikan nama aktif pada indikator HUD 'GILIRAN'.")
print("   - Saat giliran Anda, gunakan Joystick Analog kiri bawah untuk menembak.")
print("   - Tarik analog untuk mengatur kekuatan/arah (dipandu garis putih).")
print()

print("--- [ LANGKAH 6: FITUR DAN ATURAN KHUSUS (DETAIL TERKECIL) ] ---")
print("1. GOAL: Masukkan bola ke dalam lubang berbendera merah di ujung kanan.")
print("2. DETEKSI OUT OF BOUNDS (OOB):")
print("   - Jika bola dipukul keluar dari batas area hijau (kiri/kanan layar),")
print("     posisi bola akan dibekukan dan dikembalikan ke posisi aman terakhir.")
print("   - Server secara otomatis memberikan penalti +1 stroke pada total pukulan.")
print("3. ANTI-STUCK SYSTEM:")
print("   - Jika bola terperangkap di lembah tajam atau berputar konstan (bug) ")
print("     lebih dari 5 detik (300 frame), koordinat bola otomatis dipaksa")
print("     berhenti untuk menghindari kemacetan alur giliran permainan.")
print("4. RE-SYNC:")
print("   - Jika terjadi kendala desinkronisasi visual antar-pemain, cukup")
print("     lakukan reload halaman browser untuk menyegarkan koneksi state.")
print()

print("=" * 65)
print(" Tips: Skrip ip.py juga otomatis memperbarui file 'ip_config.js'! ")
print("=" * 65)
